In [1]:
import numpy as np

# 1. 행렬

## 1) 행렬 만들기

- 행렬 만들 때 기본적으로 **np.array** 를 사용 해서 만들고, **리스트 or 튜플** 형태를 받아서 사용함.

In [ ]:
_list = [1,2,3]
np.array(_list)

array([1, 2, 3])

In [ ]:
_list1 = [1,2,3]
_list2 = [4,5,6]
np.array([_list1,_list2]) # 리스트를 따로 받을 때는 대괄호 한번씩 더해줘야함

array([[1, 2, 3],
       [4, 5, 6]])

### 넘파이 행렬 함수 (1)

- **reshape**

In [ ]:
a=np.array([11,22,33,44,55,66])
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

- **arange**

In [ ]:
a = np.arange(5)
b = np.arange(1,5)
a,b

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4]))

- **linspace**

In [ ]:
np.linspace(0,1,12) #0부터1까지 12개로 나눠서 배열선언

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

- **역행렬 + 전치행렬 + 행렬곱**

In [ ]:
A=np.arange(4).reshape(2,2)
A.T #T는 전치행렬을 구해줌

array([[0, 1],
       [2, 3]])

In [ ]:
A=np.arange(4).reshape(2,2)
np.linalg.inv(A) #np.linalg.inv는 역행렬을 구해줌

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
A=np.arange(4).reshape(2,2)
np.linalg.inv(A)
A@np.linalg.inv(A) #@는 행렬곱을 구해줌

array([[1., 0.],
       [0., 1.]])

### 넘파이 행렬함수 (2)

- **zeros**

In [ ]:
np.zeros(3)

array([0., 0., 0.])

- **ones**

In [ ]:
a = np.ones(3)
b = np.ones((3,3))
a,b

(array([1., 1., 1.]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

- **eye**

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- **diag**

In [ ]:
np.diag([2,3,4,-2])

array([[ 2,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  4,  0],
       [ 0,  0,  0, -2]])

## 행렬 인덱싱

In [ ]:
A = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2 = np.array(A)
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [ ]:
A2[[0,2],:] #1행,3행 추출

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
A2[:,[0]]

array([[ 1],
       [-1],
       [ 5],
       [-5]])

In [ ]:
A2[:,0]

array([ 1, -1,  5, -5])