In [1]:
from IPython.core.display import HTML
import numpy as np
import pandas as pd

`*` **중요** `*`

사실 파이썬의 list도 클래스 종류임

리스트 입력 값은 `__init__` 메소드의 입력값

In [33]:
a = '123'
list(a)

['1', '2', '3']

In [39]:
a = list()
a.__init__('123')
a

['1', '2', '3']

In [ ]:
a = list()
a

In [55]:
a= np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [42]:
a.__str__()

'[[0 1]\n [2 3]]'

In [43]:
a.__repr__()

'array([[0, 1],\n       [2, 3]])'

In [59]:
print(a.__str__())

[[0 1]
 [2 3]]


## `__str__` 과 `__repr__`의 차이

print(ins) == print(ins.`__str__`)

In [63]:
a= np.arange(4).reshape(2,2)
(print(a),print(a.__str__()))

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


(None, None)

ins = print(ins.`__repr__`)

In [70]:
a= np.arange(4).reshape(2,2)
a,print(a.__repr__())

array([[0, 1],
       [2, 3]])


(array([[0, 1],
        [2, 3]]),
 None)

## 13wk-2 과제

`1.` Student 클래스 설계

In [92]:
class Student:
  def __init__(self,name,age,semester):
    self.name = name
    self.age = age
    self.semester = semester
  def __str__(self):
    print_str = '''이름: {}\n나이: {}\n학기: {}'''.format(self.name,self.age,self.semester)
    return print_str

In [93]:
# 사용 예시
boram = Student(name='김보람', age=20, semester=1)
print(boram)

이름: 김보람
나이: 20
학기: 1


In [95]:
# 사용 예시
Paul = Student(name='김 폴', age=22, semester=2)
print(Paul)

이름: 김 폴
나이: 22
학기: 2


`2.` RPS 클래스 설계 (1)

In [132]:
class RPS:
  def __init__(self,candidate):
    self.candidate = candidate
    self.actions = []
  def pick(self):
    self.actions.append(np.random.choice(self.candidate))
  def _repr_html_(self):
    html_str = '''
      낼 수 있는 패: {}<br>
      기록: {}
      '''
    return html_str.format(self.candidate,self.actions)

In [134]:
a = RPS(['가위','바위','보'])
a.pick()
a

In [128]:
a = RPS(['가위','바위','보'])

In [129]:
a.candidate, a.actions

(['가위', '바위', '보'], [])

In [130]:
a

In [137]:
for i in range(5):
    a.pick()

`3.` RPS 설계 (2)

In [202]:
a = RPS(['가위','보'])
b = RPS(['가위'])
rslt = []
for i in range(100):
  a.pick()
  b.pick()
  if a.actions[-1] =='가위' and b.actions[-1] =='가위':
    rslt.append('-')
  elif a.actions[-1] =='보' and b.actions[-1] =='가위':
    rslt.append('b')
  else:
    rslt.append('a')

In [203]:
{'a의승리':rslt.count('a'),'무승부':rslt.count('-'),'b의승리':rslt.count('b')}

{'a의승리': 0, '무승부': 53, 'b의승리': 47}

`4.`RPS설계 (3)

In [222]:
a = RPS(['가위','보'])
b = RPS(['가위','바위'])
rslt = []
for i in range(100):
  a.pick()
  b.pick()
  if a.actions[-1] =='가위' and b.actions[-1] =='가위':
    rslt.append('-')
  elif a.actions[-1] =='보' and b.actions[-1] =='가위':
    rslt.append('b')
  elif a.actions[-1] =='가위' and b.actions[-1] =='바위':
    rslt.append('b')
  else:
    rslt.append('a')

In [223]:
{'a의승리':rslt.count('a'),'무승부':rslt.count('-'),'b의승리':rslt.count('b')}

{'a의승리': 21, '무승부': 29, 'b의승리': 50}